apiVersion: v1
kind: Service
metadata:
  name: eve-incursions
  namespace: eve-incursions
  labels:
    app: eve-incursions
spec:
  type: ClusterIP
  selector:
    app: eve-incursions
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
