apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eve-incursions
  namespace: eve-incursions
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod-dns01"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - eve-incursions.lab.hq.solidrust.net
    secretName: eve-incursions-tls
  rules:
  - host: eve-incursions.lab.hq.solidrust.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eve-incursions
            port:
              number: 80
